channels:
- bioconda
- conda-forge
- defaults
- r
dependencies:
# https://github.com/ContinuumIO/anaconda-issues/issues/4656
- r-base
- r-broom
- r-caret
- r-cowplot
- r-dendextend
- r-devtools
- r-dt
- r-extrafont
- r-flexdashboard
- r-ggbiplot
- r-ggpubr
- r-ggthemes
- r-gridbase
- r-gridextra
- r-gtable
- r-heatmaply
- r-lubridate
- r-plotly
- r-psych
- r-rcolorbrewer
- r-scales
- r-shiny
- r-shinythemes
- r-shinywidgets
- r-tidyr
- r-tidyverse
- r-wesanderson
- r-zoo
