channels:
- bioconda
- conda-forge
- defaults
- r
dependencies:
# https://github.com/ContinuumIO/anaconda-issues/issues/4656
- r-base=4.0
- r-broom
- r-caret
- r-corrr
- r-cowplot
- r-dendextend
- r-devtools
- r-dt
- r-extrafont
- r-flexdashboard
- r-fmsb
- r-ggbiplot
- r-ggforce
- r-ggpubr
- r-ggthemes
- r-gridbase
- r-gridextra
- r-gt
- r-gtsummary
- r-gtable
- r-heatmaply
- r-lubridate
- r-plotly
- r-psych
- r-rcolorbrewer
- r-readxl
- r-scales
- r-reshape2
- r-shiny
- r-shinythemes
- r-shinywidgets
- r-survival
- r-survminer
- r-tidyr
- r-tidyverse
- r-wesanderson
- r-zoo
