channels:
- bioconda
- conda-forge
- defaults
- r
dependencies:
# https://github.com/ContinuumIO/anaconda-issues/issues/4656
- r-base
- r-devtools
- r-flexdashboard
- r-heatmaply
- r-plotly
- r-shiny
- r-shinywidgets
- r-tidyverse
