channels:
- bioconda
- conda-forge
- defaults
- r
dependencies:
# https://github.com/ContinuumIO/anaconda-issues/issues/4656
- r-base
- r-devtools
- r-dt
- r-flexdashboard
- r-gridbase
- r-gridextra
- r-gtable
- r-heatmaply
- r-lubridate
- r-plotly
- r-rcolorbrewer
- r-scales
- r-shiny
- r-shinywidgets
- r-tidyverse
